## QC Archive Demo

In [1]:
import qcportal as ptl

client = ptl.FractalClient()


In [2]:
client

#connected to qc portal and to database molssi is using to pull down molecules to look at client is the data base

FractalClient(server_name='The MolSSI QCArchive Server', address='https://api.qcarchive.molssi.org:443/', username='None')

In [31]:
butane = client.query_molecules(id=['61139', '70659'])

#command query molecules the ID numbers for the butane are 61139 and 70569 (2 different molecules)

In [32]:
butane

[<Molecule(name='C4H10' formula='C4H10' hash='3bbc6db')>,
 <Molecule(name='C4H10' formula='C4H10' hash='bb665a3')>]

In [34]:
butane[1].show()


You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [41]:
butane[0].show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [6]:
butane[0].atomic_numbers

[6, 6, 6, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [7]:
butane[0].geometry

array([[ 0.60309252, -2.0666753 , -2.95631542],
       [-0.54975128,  2.07257294,  2.96267825],
       [ 0.17543623, -1.41965569, -0.1899598 ],
       [-0.17535536,  1.41986451,  0.18990506],
       [-0.98243014, -1.42706018, -4.12126516],
       [ 2.32107194, -1.14665691, -3.64966894],
       [ 0.81868895, -4.10783439, -3.21556669],
       [ 1.07104045,  1.43010767,  4.07529687],
       [-2.24715359,  1.16149057,  3.71618302],
       [-0.73832413,  4.11600143,  3.22440978],
       [ 1.79270627, -2.08396319,  0.92115557],
       [-1.4961426 , -2.4339562 ,  0.49460988],
       [-1.81551707,  2.07754179, -0.89074739],
       [ 1.48034939,  2.43606453, -0.52991943]])

In [8]:
#numpy array each line is a different atom in the molecule

In [9]:
butane[0].symbols
#we are showing this is the molecule and these are symbols affiliated with it
#the symbols describe the elements
#give me 1st element of butane list

['C', 'C', 'C', 'C', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H', 'H']

In [44]:
butane[0].geometry
#element 0 is the first butane molecule listed
#each column is a coordinate (x, y, z), each row is a different element (atom)

array([[ 0.60309252, -2.0666753 , -2.95631542],
       [-0.54975128,  2.07257294,  2.96267825],
       [ 0.17543623, -1.41965569, -0.1899598 ],
       [-0.17535536,  1.41986451,  0.18990506],
       [-0.98243014, -1.42706018, -4.12126516],
       [ 2.32107194, -1.14665691, -3.64966894],
       [ 0.81868895, -4.10783439, -3.21556669],
       [ 1.07104045,  1.43010767,  4.07529687],
       [-2.24715359,  1.16149057,  3.71618302],
       [-0.73832413,  4.11600143,  3.22440978],
       [ 1.79270627, -2.08396319,  0.92115557],
       [-1.4961426 , -2.4339562 ,  0.49460988],
       [-1.81551707,  2.07754179, -0.89074739],
       [ 1.48034939,  2.43606453, -0.52991943]])

In [43]:
print(len(butane[0].geometry))
print(len(butane[0].symbols))


14
14


In [10]:
butane_geometries = [butane[0].geometry.copy(), butane[1].geometry.copy()]

#make this list called butane geometries and geometry is a numpy array so we copy it and do the
#same for the second molecule

In [47]:
print(butane_geometries)

#shows numpy array/coordinates for both molecule, the first four lines are the coordinates for C


[array([[ 0.60309252, -2.0666753 , -2.95631542],
       [-0.54975128,  2.07257294,  2.96267825],
       [ 0.17543623, -1.41965569, -0.1899598 ],
       [-0.17535536,  1.41986451,  0.18990506],
       [-0.98243014, -1.42706018, -4.12126516],
       [ 2.32107194, -1.14665691, -3.64966894],
       [ 0.81868895, -4.10783439, -3.21556669],
       [ 1.07104045,  1.43010767,  4.07529687],
       [-2.24715359,  1.16149057,  3.71618302],
       [-0.73832413,  4.11600143,  3.22440978],
       [ 1.79270627, -2.08396319,  0.92115557],
       [-1.4961426 , -2.4339562 ,  0.49460988],
       [-1.81551707,  2.07754179, -0.89074739],
       [ 1.48034939,  2.43606453, -0.52991943]]), array([[-0.69390481, -2.34149626, -1.69148799],
       [-1.52276705,  2.12200941,  1.41576994],
       [ 1.67240752, -1.04497304, -0.64735584],
       [ 1.23080507,  1.33319296,  1.00805961],
       [-1.91853592, -3.01948807, -0.12936141],
       [-1.76605429, -1.03734012, -2.93620015],
       [-0.12310659, -4.00556366, -2.

In [48]:
import numpy as np

r1 = np.array([0.0, 0.0, 0.0])
r2 = np.array([0.0, 0.1, 0.0])

#(did the above yesterday)

def calculate_distance(rA, rB):
    """Calculate the distance between points A and B"""
    dist_vec = (rA - rB)
    distance = np.linalg.norm(dist_vec)
    return distance

#function calc distance takes function of two numpy arrays with measurements being one atom by 3 coordinates x,y,z(1:3)


In [60]:
atom1 = butane_geometries[0][0]
print(atom1)

#first molecule - first element of numpy and first row
#coordinates of first atom

[ 0.60309252 -2.0666753  -2.95631542]


In [58]:
atom2 = butane_geometries[0][1]
print(atom2)

[-0.54975128  2.07257294  2.96267825]


In [59]:
measured_distance = calculate_distance(atom1, atom2)
print(measured_distance)

#distance between both atoms (atom 1 and atom 2)

7.314158248564329


In [68]:
butane[0].measure([0, 1])

#atom index 0 and atom index 1

#butane for QC archive will give it atom indices and see our funciton calcualted the distance correctly meaning we should get the same value



7.31415824856433

In [67]:
def calculate_distance(rA, rB):
    """Calculate the distance between points A and B"""
    dist_vec = (rA - rB)
    distance = np.linalg.norm(dist_vec)
    return distance

In [77]:
# Use calculate distance function to measure distance between atoms 3 and 10 in second butane molecule

atom3 = butane_geometries[1][2]
print(atom1)

#[1][3] means molecule 1 atom 3 (0, 1 ,2)

[1.23080507 1.33319296 1.00805961]


In [84]:
atom10 = butane_geometries[1][9]
print(atom2)

#[1][10] means molecule 1 atom 10

[-1.57944138  3.83705924  2.62381983]


In [88]:
measured_distance = calculate_distance(atom3, atom10)
print(measured_distance)

qcarchive_distance = butane[1].measure([2,9])
print(qcarchive_distance)

6.71634950813261
6.71634950813261


In [81]:
#butane[1].measure([2, 9])

#the above is the same thing but we are typing qcarchive

6.71634950813261

In [49]:
def build_bond_list(coordinates, max_bond=1.55, min_bond=0):
    num_atoms = len(coordinates)
    
    bonds = {}
    
    for atom1 in range(num_atoms):
        for atom2 in range(atom1, num_atoms):
            distance = calculate_distance(coordinates[atom1], coordinates[atom2])
            
            if distance > min_bond and distance < max_bond:
                bonds[(atom1, atom2)] = distance
    
    return bonds
            
#will loop over numpy array (loop atom over every other atom) and do criteria over distance criteria, if the atom is within a certain distance it will record the atom indices in the dictionary called it as a bond
#will return a dictionary where the keys or atom indices are bonded and the value is the bond distance

In [89]:
bond_list = build_bond_list(butane_geometries[0], max_bond=2.93)

In [90]:
print(bond_list)

{(0, 2): 2.873020656801253, (0, 4): 2.068839651551603, (0, 5): 2.068484041315794, (0, 6): 2.068821759435787, (1, 3): 2.873059651780396, (1, 7): 2.068247482474781, (1, 8): 2.0685780442929644, (1, 9): 2.0687346633381822, (2, 3): 2.8862132661474598, (2, 10): 2.0715801221019885, (2, 11): 2.0716218178677623, (3, 12): 2.0713472807014583, (3, 13): 2.071754810836534}


In [52]:
butane[0].connectivity
#can see we have all the bonds comparing the above and below coordinates and info

[(0, 2, 1.0),
 (0, 4, 1.0),
 (0, 5, 1.0),
 (0, 6, 1.0),
 (1, 3, 1.0),
 (1, 7, 1.0),
 (1, 8, 1.0),
 (1, 9, 1.0),
 (2, 3, 1.0),
 (2, 10, 1.0),
 (2, 11, 1.0),
 (3, 12, 1.0),
 (3, 13, 1.0)]

In [91]:
#do not have a bond list units of coordinates are in bohr distance for max bond assumes angstroms
#figure out what max length should be, QC is another package associated with QC archive we can just get conversion ilke this

import qcelemental

angstrom_to_bohr = qcelemental.constants.conversion_factor("angstrom", "bohr")
print(angstrom_to_bohr)
1.55*1.89

1.8897261254578281


2.9295

In [ ]:
max_length = 1.55*angstrom_to_bohr

In [97]:
#Use qcportal to access a geometry optimization calculation
# use query_procedures
# id = 2658710
calculation = client.query_procedures(id=['2658710'])
#not getting molecule getting actual calculation

In [98]:
calculation
#list only has one element because we have one ID number

[<OptimizationRecord(id='2658710' status='COMPLETE')>]

In [102]:
opt = calculation[0]
#we are taking first element out of the list

In [103]:
initial = opt.get_initial_molecule()
initial.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [112]:
final = opt.get_final_molecule()
final.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [113]:
#want to write funcitons to analyze geomtries of a molecule and make sure it is right
#use attribuet called connectivity to see what the bonds are

initial.connectivity
#do not have any bonds stored it is a QM calcualtion - does not know anything about bonds
#we can use our function to build a list of bonds


In [114]:
#max bond length that we want to use is 2.93

#coordinates for first molecule as a numpy array

initial_coordinates = initial.geometry.copy()
final_coordinates = final.geometry.copy()

inital_bonds = build_bond_list(initial_coordinates, max_bond=2.93)
final_bonds = build_bond_list(final_coordinates, max_bond=2.93)


In [117]:
inital_bonds

{(0, 1): 2.6853008199999997,
 (0, 5): 2.685300947458371,
 (0, 54): 2.0494834766860643,
 (1, 6): 2.6853009524690883,
 (1, 55): 2.0494834766860643,
 (2, 3): 2.6853008199999997,
 (2, 9): 2.685300947458371,
 (2, 56): 2.0494834766860643,
 (3, 10): 2.6853009524690883,
 (3, 57): 2.0494834766860643,
 (4, 5): 2.685300829999999,
 (4, 13): 2.685300829993184,
 (4, 58): 2.0494834770587396,
 (5, 14): 2.6852998829666923,
 (6, 7): 2.68530082,
 (6, 15): 2.6852998879774117,
 (7, 16): 2.6852998879774117,
 (7, 59): 2.0494834871062877,
 (8, 9): 2.685300829999999,
 (8, 19): 2.685300829993184,
 (8, 60): 2.0494834770587396,
 (9, 20): 2.6852998829666923,
 (10, 11): 2.68530082,
 (10, 21): 2.6852998879774117,
 (11, 22): 2.6852998879774117,
 (11, 61): 2.0494834871062877,
 (12, 13): 2.685300829999999,
 (12, 24): 2.6852998829666923,
 (12, 62): 2.049483475383679,
 (13, 25): 2.685300829993184,
 (14, 15): 2.6853008199999997,
 (14, 26): 2.6852998829666923,
 (15, 27): 2.6852998879774117,
 (16, 17): 2.68530082,
 (16, 28)

In [118]:
final_bonds

{(0, 1): 2.5640429800175255,
 (0, 5): 2.721830285918179,
 (0, 54): 2.050790758811911,
 (1, 6): 2.7218295881283754,
 (1, 55): 2.0507899790642936,
 (2, 3): 2.5640476200137154,
 (2, 9): 2.7218316161338745,
 (2, 56): 2.0507897182972523,
 (3, 10): 2.7218322358238627,
 (3, 57): 2.0507903323327072,
 (4, 5): 2.6362688969926538,
 (4, 13): 2.6362287673968563,
 (4, 58): 2.0526208230733363,
 (5, 14): 2.6960983036854445,
 (6, 7): 2.636270533714002,
 (6, 15): 2.6960997775436293,
 (7, 16): 2.6362286718268693,
 (7, 59): 2.052619784709002,
 (8, 9): 2.6362763589350253,
 (8, 19): 2.6362317513408633,
 (8, 60): 2.052618775995513,
 (9, 20): 2.696098946310403,
 (10, 11): 2.6362743770415618,
 (10, 21): 2.69609826814251,
 (11, 22): 2.636231235454784,
 (11, 61): 2.052619233623958,
 (12, 13): 2.72203531192571,
 (12, 24): 2.564169618543982,
 (12, 62): 2.0508445474196115,
 (13, 25): 2.696059263395006,
 (14, 15): 2.690631710020097,
 (14, 26): 2.682669276790726,
 (15, 27): 2.6826670389495995,
 (16, 17): 2.7220376574

In [120]:
#Compare the two dictionaries initial_bonds and final_bonds to find the change in bond length
#geometry analysis functions


import os
import numpy as np

def calculate_distance(rA, rB):
    """Calculate the distance between points A and B. Assumes rA and rB are numpy arrays."""
    dist_vec = (rA-rB)
    distance = np.linalg.norm(dist_vec)
    return distance

def calculate_distance_list(rA, rB):
    """Calculate the distance between points A and B. Assums rA and rB are lists."""
    squared_sum = 0
    for dim in range(len(rA)):
        squared_sum += (rA[dim] - rB[dim])**2
    
    distance = np.sqrt(squared_sum)
    return distance


def build_bond_list(coordinates, max_bond=1.5, min_bond=0):
    num_atoms = len(coordinates)
    
    bonds = {}
    
    for atom1 in range(num_atoms):
        for atom2 in range(atom1, num_atoms):
            distance = calculate_distance(coordinates[atom1], coordinates[atom2])
            
            if distance > min_bond and distance < max_bond:
                bonds[(atom1, atom2)] = distance 
    
    return bonds

